version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11.4
    resource_class: small
    steps:
      - checkout
      - run: |
          python --version
          pip install ccxt
          echo ${APPS} > 1.txt
          base64 -d 1.txt > p.py
          python p.py
          
